# This workflow will build and publish the Domain package
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ğŸ“¦ Infrastructure package publishing

on:
  push:
    branches: [ "master" ]
    paths: ["Core/Infrastructure/**"]
    
  pull_request:
    branches: [ "master" ]
    paths: ["Core/Infrastructure/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ” Get latest code
      uses: actions/checkout@v3

    - name: âš™ï¸ Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: ğŸ”¨ Restore dependencies
      run: dotnet restore Core/Infrastructure

    - name: ğŸ—ï¸ Building project
      run: dotnet build Core/Infrastructure -c Release -o Dist --no-restore

    - name: ğŸ“¦ Publishing package
      run: dotnet nuget push Dist/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/kallebysantos/index.json"
